/**
 * Emit an IR as a Promtail (`promtail.yml`) configuration.
 *
 * The shape we produce:
 *
 *   clients:
 *     - url: http://loki:3100/loki/api/v1/push
 *
 *   scrape_configs:
 *     - job_name: <from IRInput.params.name>
 *       <input-type>: { ... }
 *       pipeline_stages:
 *         - <stage-type>: { ... }
 *
 * Cross-dialect translation (e.g. rsyslog → promtail) fans every input
 * into a single job per source-type. Lookup tables become `template` or
 * `regex` stages with comments pointing at how the operator should
 * realise them — Promtail's pipeline-stages language is rich enough to
 * do lookup-shaped substitution but the syntax doesn't 1:1 map from
 * rsyslog's `lookup()`.
 */

import type { IRModel, IRStatement } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';
import type { EmitLookupData, EmitResult } from '../types.js';
import * as yaml from 'js-yaml';

export function emit(
  model: IRModel,
  opts?: { lookupTables?: Record<string, EmitLookupData> }
): EmitResult {
  const diagnostics: Diagnostic[] = [];
  const lookups = opts?.lookupTables ?? {};

  const clients = buildClients(model);
  const scrapeConfigs = buildScrapeConfigs(model, lookups, diagnostics);

  const doc: Record<string, unknown> = {
    server: { http_listen_port: 9080, grpc_listen_port: 0 },
    positions: { filename: '/tmp/positions.yaml' },
    clients,
    scrape_configs: scrapeConfigs
  };

  const body = yaml.dump(doc, { noRefs: true, lineWidth: 120, sortKeys: false });
  const output = `# Generated by logflow-sim convert\n# Source dialect: ${model.dialect ?? 'unknown'}\n\n${body}`;
  return {
    output,
    files: [{ path: 'promtail.yml', content: output }],
    diagnostics
  };
}

function buildClients(model: IRModel): Record<string, unknown>[] {
  const urls = new Set<string>();
  for (const o of model.outputs) {
    const url = o.params['url'];
    if (typeof url === 'string') urls.add(url);
  }
  if (urls.size === 0) urls.add('http://loki:3100/loki/api/v1/push');
  return [...urls].map((url) => ({ url }));
}

function buildScrapeConfigs(
  model: IRModel,
  lookups: Record<string, EmitLookupData>,
  diagnostics: Diagnostic[]
): Record<string, unknown>[] {
  const configs: Record<string, unknown>[] = [];
  for (const inp of model.inputs) {
    const jobName = String(inp.params['name'] ?? inp.id);
    const cfg: Record<string, unknown> = { job_name: jobName };
    const t = inp.type.toLowerCase();
    if (t === 'imudp' || t === 'imtcp' || t === 'imptcp' || t === 'syslog') {
      cfg.syslog = {
        listen_address: `0.0.0.0:${inp.port ?? 1514}`,
        labels: { job: jobName }
      };
    } else if (t === 'imfile' || t === 'log' || t === 'file' || t === 'filelog') {
      const paths = inp.params['paths'];
      const target =
        typeof paths === 'string' ? paths.split(',')[0] : Array.isArray(paths) ? String(paths[0]) : '/var/log/*.log';
      cfg.static_configs = [
        { targets: ['localhost'], labels: { job: jobName, __path__: target } }
      ];
    } else if (t === 'imjournal' || t === 'journald') {
      cfg.journal = { json: false, max_age: '12h', labels: { job: jobName } };
    } else {
      cfg.static_configs = [{ targets: ['localhost'], labels: { job: jobName } }];
    }

    const stages: Record<string, unknown>[] = [];
    for (const lt of model.lookupTables) {
      const data = lookups[lt.name];
      if (!data || !data.entries) continue;
      // Promtail's `template` stage can build a label from a regex extract
      // + a lookup-shape, but the cleanest cross-dialect emit is a `match`
      // stage with a comment + the table inlined. The operator picks the
      // promtail-idiomatic shape based on which label they want.
      stages.push({
        match: {
          selector: `{job="${jobName}"}`,
          stages: [
            {
              // Note for the operator — Promtail stages don't have a
              // first-class "lookup table" primitive; this is documented
              // so they can convert it to a `template` stage by hand.
              template: {
                source: lt.name,
                template: `{{ "${data.nomatch ?? ''}" }}  // logflow-sim: convert this to your real lookup mapping`
              }
            }
          ]
        }
      });
      diagnostics.push({
        severity: 'info',
        message:
          `Promtail emit: lookup table "${lt.name}" emitted as a stub \`template\` stage under ` +
          `job "${jobName}". Promtail has no first-class lookup-table primitive; convert to a ` +
          `match/template chain or pre-process upstream.`,
        source: { file: '<emit>', line: 0, col: 0, offset: 0, length: 0 },
        code: 'I_PROMTAIL_LOOKUP_STUB'
      });
    }

    // From rsyslog: synthesize `regex` + `labels` stages for if-condition
    // shaped routing. Best-effort; deeply nested conditions don't emit
    // anything (the IR walking is intentionally shallow here).
    for (const rs of model.rulesets) {
      for (const s of rs.statements) {
        if (s.kind === 'If' && s.then.length > 0 && hasOmFile(s.then)) {
          // Heuristic: surface the condition as a comment label so the
          // operator can decide whether to translate it to a stage chain.
          stages.push({
            labels: {
              [`from_if_${rs.name}`]: ''
            }
          });
        }
      }
    }
    if (stages.length > 0) cfg.pipeline_stages = stages;
    configs.push(cfg);
  }

  if (configs.length === 0) {
    configs.push({
      job_name: 'fallback',
      static_configs: [{ targets: ['localhost'], labels: { job: 'fallback', __path__: '/var/log/*.log' } }]
    });
  }
  return configs;
}

function hasOmFile(stmts: IRStatement[]): boolean {
  for (const s of stmts) {
    if (s.kind === 'Action' && s.actionKind === 'omfile') return true;
    if (s.kind === 'If') {
      if (hasOmFile(s.then)) return true;
      if (s.else && hasOmFile(s.else)) return true;
    }
  }
  return false;
}
