import type { IRModel } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';

/**
 * Emit a normalized IR as a Fluent Bit `.conf` file.
 *
 * Mapping:
 *   IRInput   → [INPUT]   Name <type>  Tag <name>  …
 *   IROutput  → [OUTPUT]  Name <driver>  Match <tag>  …
 *   IRModule  with load starting with "filter:" → [FILTER]   Name <type>  Match <tag>  …
 *   IRGlobals → [SERVICE]
 *
 * Routing in Fluent Bit is tag-based, so we tag each input with a unique
 * tag derived from its name and wire outputs/filters to match those tags
 * via the `Match` parameter.
 */
export function emit(model: IRModel): { output: string; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const lines: string[] = [];
  lines.push('# Generated by logflow-sim convert');
  lines.push(`# Source dialect: ${model.dialect}`);
  lines.push('');

  // [SERVICE]
  if (Object.keys(model.globals.params).length > 0) {
    lines.push('[SERVICE]');
    for (const [k, v] of Object.entries(model.globals.params)) {
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        if (k.startsWith('__')) continue;
        lines.push(`    ${pad(k)}${String(v)}`);
      }
    }
    lines.push('');
  }

  // Build a tag table — every input gets a stable tag we can match against.
  const tagFor = new Map<string, string>();
  for (const inp of model.inputs) {
    const existing = inp.params['tag'] ?? inp.params['_tag'];
    const tag =
      typeof existing === 'string' && existing
        ? existing
        : `${sanitizeTag(inp.type)}.${inp.port ?? 'in'}`;
    tagFor.set(inp.id, tag);
  }

  // [INPUT] blocks
  for (const inp of model.inputs) {
    lines.push('[INPUT]');
    lines.push(`    ${pad('Name')}${mapInputType(inp.type)}`);
    lines.push(`    ${pad('Tag')}${tagFor.get(inp.id)}`);
    if (inp.port !== undefined) lines.push(`    ${pad('Port')}${inp.port}`);
    for (const [k, v] of Object.entries(inp.params)) {
      if (['name', 'tag', '_tag', 'type', 'port'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${pad(titleize(k))}${String(v)}`);
      }
    }
    lines.push('');
  }

  // [FILTER] blocks — promoted from `IRModule` entries whose load starts
  // with "filter:".
  for (const mod of model.modules) {
    if (!mod.load.startsWith('filter:')) continue;
    lines.push('[FILTER]');
    const name = mod.load.replace(/^filter:/, '');
    lines.push(`    ${pad('Name')}${name}`);
    if (!mod.params['match']) lines.push(`    ${pad('Match')}*`);
    for (const [k, v] of Object.entries(mod.params)) {
      if (k === 'name') continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${pad(titleize(k))}${String(v)}`);
      }
    }
    lines.push('');
  }

  // For rsyslog-shaped IR (rulesets+actions): synthesize one OUTPUT per
  // distinct action target, with `Match *` to receive every record. We
  // could be smarter (per-input Match patterns) but `*` is safe.
  const emittedOutputKeys = new Set<string>();

  for (const out of model.outputs) {
    lines.push('[OUTPUT]');
    lines.push(`    ${pad('Name')}${mapOutputDriver(out.driver)}`);
    if (!out.params['match']) lines.push(`    ${pad('Match')}*`);
    for (const [k, v] of Object.entries(out.params)) {
      if (k === 'name') continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${pad(titleize(k))}${String(v)}`);
      }
    }
    lines.push('');
    emittedOutputKeys.add(out.name);
  }

  // Walk rsyslog rulesets to surface their actions as fallback outputs.
  for (const rs of model.rulesets) {
    walkAndEmit(rs.statements, emittedOutputKeys, lines);
  }

  if (model.routes.length > 0 || model.outputs.length > 0) {
    // Done.
  } else if (model.rulesets.length > 0 && emittedOutputKeys.size === 0) {
    diagnostics.push({
      severity: 'info',
      message:
        'Source dialect had rulesets but no actions could be mapped — output config has no [OUTPUT] sections.',
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_CONVERT_NO_OUTPUTS'
    });
  }

  return { output: lines.join('\n') + '\n', diagnostics };
}

function walkAndEmit(
  stmts: import('../../ir/model.js').IRStatement[],
  emitted: Set<string>,
  lines: string[]
): void {
  for (const s of stmts) {
    if (s.kind === 'If') {
      walkAndEmit(s.then, emitted, lines);
      if (s.else) walkAndEmit(s.else, emitted, lines);
      continue;
    }
    if (s.kind !== 'Action') continue;
    const key = JSON.stringify(s.params);
    if (emitted.has(key)) continue;
    emitted.add(key);
    lines.push('[OUTPUT]');
    lines.push(`    ${pad('Name')}${mapOutputDriver(s.actionType || s.actionKind)}`);
    lines.push(`    ${pad('Match')}*`);
    for (const [k, v] of Object.entries(s.params)) {
      if (k === 'type') continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${pad(titleize(k))}${String(v)}`);
      }
    }
    lines.push('');
  }
}

function mapInputType(t: string): string {
  // Fluent Bit input names. Common rsyslog/syslog-ng → fluentbit mappings.
  const m: Record<string, string> = {
    imudp: 'syslog',
    imtcp: 'syslog',
    imptcp: 'syslog',
    udp: 'syslog',
    tcp: 'syslog',
    imfile: 'tail',
    imjournal: 'systemd',
    imuxsock: 'unix_socket'
  };
  return m[t.toLowerCase()] ?? t;
}

function mapOutputDriver(d: string): string {
  const m: Record<string, string> = {
    omfile: 'file',
    omfwd: 'syslog',
    omkafka: 'kafka',
    omhttp: 'http',
    omelasticsearch: 'es'
  };
  return m[d.toLowerCase()] ?? d;
}

function sanitizeTag(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, '_').toLowerCase();
}

function titleize(s: string): string {
  return s
    .split(/[_-]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('_');
}

function pad(label: string): string {
  return label.padEnd(16, ' ');
}
