/**
 * Emit an IR as a Filebeat (`filebeat.yml`) configuration.
 *
 * Filebeat has a single output block (any of `output.elasticsearch`,
 * `output.logstash`, `output.kafka`, …) so cross-dialect emit collapses
 * the model's possibly-many sinks into one. We pick the first non-file
 * output if available — file is rarely what you actually want in
 * Filebeat — and emit the rest as commented hints so the operator can
 * choose.
 *
 * Lookup tables don't have a clean Filebeat equivalent at the routing
 * layer (Filebeat enrichment lives in `processors:`). We emit the table
 * data as a `fields:` hint comment per input so the operator can wire
 * an add_fields / script processor by hand.
 */

import type { IRModel, IRStatement } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';
import type { EmitLookupData, EmitResult } from '../types.js';
import * as yaml from 'js-yaml';

export function emit(
  model: IRModel,
  opts?: { lookupTables?: Record<string, EmitLookupData> }
): EmitResult {
  const diagnostics: Diagnostic[] = [];
  const lookups = opts?.lookupTables ?? {};

  // Inputs
  const fbInputs: Record<string, unknown>[] = [];
  for (const inp of model.inputs) {
    fbInputs.push(buildInput(inp));
  }
  // Action-centric source dialects (rsyslog) don't expose inputs that map
  // cleanly to Filebeat's file/syslog types; we infer one tail-style input
  // per unique file action so the emitted config does *something* sensible.
  const seenPaths = new Set<string>();
  function walk(stmts: IRStatement[]): void {
    for (const s of stmts) {
      if (s.kind === 'If') {
        walk(s.then);
        if (s.else) walk(s.else);
        continue;
      }
      if (s.kind !== 'Action') continue;
      if (s.actionKind !== 'omfile') continue;
      const p = String(s.params['file'] ?? s.params['dynafile'] ?? '');
      if (!p || seenPaths.has(p)) continue;
      seenPaths.add(p);
      fbInputs.push({ type: 'log', paths: [p] });
    }
  }
  for (const rs of model.rulesets) walk(rs.statements);

  // Processors — pass through what looks like a processor:* IRModule plus
  // a final `add_fields` per lookup table so downstream Elastic
  // pipelines can resolve by `programname`/`hostname` selector.
  const processors: Record<string, unknown>[] = [];
  for (const mod of model.modules) {
    if (!mod.load.startsWith('processor:')) continue;
    const type = mod.load.split(':', 2)[1];
    processors.push({ [type]: stripInternal(mod.params) });
  }
  for (const lt of model.lookupTables) {
    const data = lookups[lt.name];
    if (!data || !data.entries) continue;
    processors.push({
      script: {
        // ECMAScript-style snippet — Filebeat 8+ accepts a JS lookup
        // body. The map literal is small for typical tables; for very
        // large ones the operator should switch to a Logstash translate
        // or Elasticsearch enrich-processor pipeline.
        lang: 'javascript',
        source:
          `function process(event) {\n` +
          `  var table = ${JSON.stringify(data.entries)};\n` +
          `  var key = event.Get("${guessLookupKeyField(lt.name)}");\n` +
          `  if (key && table[key]) event.Put("${lt.name}", table[key]);\n` +
          `  else event.Put("${lt.name}", ${JSON.stringify(data.nomatch ?? '')});\n` +
          `}`
      }
    });
    if (Object.keys(data.entries).length > 200) {
      diagnostics.push({
        severity: 'warning',
        message:
          `Filebeat emit: lookup table "${lt.name}" has ${Object.keys(data.entries).length} ` +
          `entries inlined into a JS processor. Consider an Elasticsearch enrich-processor ` +
          `for large tables — JS scripts run per-event.`,
        source: { file: '<emit>', line: 0, col: 0, offset: 0, length: 0 },
        code: 'W_FILEBEAT_LOOKUP_BIG'
      });
    }
  }

  // Output. Prefer Elasticsearch when the source dialect had one, then
  // Logstash, then Kafka. Fall back to console for an obviously-broken
  // model so the resulting config still boots Filebeat in `-e` mode.
  const outputs = pickBestOutput(model);
  const doc: Record<string, unknown> = {
    'filebeat.inputs': fbInputs.length > 0 ? fbInputs : [{ type: 'log', paths: ['/var/log/*.log'] }],
    ...(processors.length > 0 ? { processors } : {}),
    ...outputs
  };

  const body = yaml.dump(doc, { noRefs: true, lineWidth: 120, sortKeys: false });
  const output = `# Generated by logflow-sim convert\n# Source dialect: ${model.dialect ?? 'unknown'}\n\n${body}`;
  return {
    output,
    files: [{ path: 'filebeat.yml', content: output }],
    diagnostics
  };
}

function buildInput(inp: { type: string; port?: number; params: Record<string, unknown> }): Record<string, unknown> {
  const t = inp.type.toLowerCase();
  if (t === 'imudp' || t === 'imtcp' || t === 'imptcp' || t === 'syslog') {
    return {
      type: 'syslog',
      protocol: t === 'imudp' ? 'udp' : 'tcp',
      host: `0.0.0.0:${inp.port ?? 514}`
    };
  }
  if (t === 'imfile' || t === 'log' || t === 'file' || t === 'filelog') {
    const paths = inp.params['paths'];
    return {
      type: 'log',
      paths: typeof paths === 'string'
        ? paths.split(',')
        : Array.isArray(paths) ? paths : [String(inp.params['file'] ?? '/var/log/*.log')]
    };
  }
  if (t === 'imjournal' || t === 'journald') return { type: 'journald' };
  if (t === 'imhttp' || t === 'http') return { type: 'http_endpoint', listen_address: '0.0.0.0', listen_port: inp.port ?? 8080 };
  // Fallback — best-effort
  return { type: t };
}

function pickBestOutput(model: IRModel): Record<string, unknown> {
  for (const o of model.outputs) {
    const t = (o.driver ?? o.actionKind).toLowerCase();
    if (t === 'elasticsearch' || t === 'omelasticsearch') {
      return { 'output.elasticsearch': { hosts: [stringParam(o.params, 'url', 'localhost:9200')] } };
    }
  }
  for (const o of model.outputs) {
    const t = (o.driver ?? o.actionKind).toLowerCase();
    if (t === 'logstash' || t === 'omfwd') {
      const host = stringParam(o.params, 'target', 'localhost');
      const port = stringParam(o.params, 'port', '5044');
      return { 'output.logstash': { hosts: [`${host}:${port}`] } };
    }
  }
  for (const o of model.outputs) {
    const t = (o.driver ?? o.actionKind).toLowerCase();
    if (t === 'kafka' || t === 'omkafka') {
      return {
        'output.kafka': {
          hosts: [stringParam(o.params, 'broker', 'localhost:9092')],
          topic: stringParam(o.params, 'topic', 'logs')
        }
      };
    }
  }
  // Walk rsyslog actions for an omfwd we can turn into an output.logstash.
  for (const rs of model.rulesets) {
    for (const found of findFirstFwd(rs.statements)) {
      const host = stringParam(found, 'target', 'localhost');
      const port = stringParam(found, 'port', '5044');
      return { 'output.logstash': { hosts: [`${host}:${port}`] } };
    }
  }
  return { 'output.console': { codec: { json: { pretty: true } } } };
}

function findFirstFwd(stmts: IRStatement[]): Record<string, unknown>[] {
  for (const s of stmts) {
    if (s.kind === 'If') {
      const t = findFirstFwd(s.then);
      if (t.length) return t;
      if (s.else) {
        const e = findFirstFwd(s.else);
        if (e.length) return e;
      }
    }
    if (s.kind === 'Action' && s.actionKind === 'omfwd') return [s.params as Record<string, unknown>];
  }
  return [];
}

function stringParam(p: Record<string, unknown>, key: string, fallback: string): string {
  const v = p[key];
  return typeof v === 'string' || typeof v === 'number' ? String(v) : fallback;
}

function stripInternal(p: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(p)) {
    if (k === 'name' || k === '_tag') continue;
    out[k] = v;
  }
  return out;
}

function guessLookupKeyField(tableName: string): string {
  // Conventions from typical SOC operators: sourcetype/programname tables
  // key on `process.name`, host-alias tables key on `host.hostname`. Anything
  // else falls back to message — a defensible last resort that the operator
  // is expected to tweak.
  const n = tableName.toLowerCase();
  if (n.includes('host') || n.includes('alias')) return 'host.hostname';
  if (n.includes('source') || n.includes('program')) return 'process.name';
  return 'message';
}
