import type {
  IRModel,
  IRRuleset,
  IRAction,
  IRStatement,
  IRIf
} from '../../ir/model.js';
import type { Expr } from '../rsyslog/parser/ast.js';
import type { Diagnostic } from '../../diagnostics.js';
import type { EmitLookupData, EmitResult } from '../types.js';

/**
 * Emit a normalized IR as a syslog-ng configuration.
 *
 * Translation strategy:
 *
 *   IRInput            → source <name> { <driver>(port(N)); };
 *   IRTemplate         → template <name> { template("..."); };
 *   IROutput / Action  → destination <name> { <driver>(...); };
 *   IRLookupTable      → parser <name> { add-contextual-data(...); };  + CSV sidecar
 *   IRRuleset          → one or more log { source; filter; parser; destination; }
 *                        blocks per ruleset, with the filter accumulated
 *                        from the if-condition path leading to each action.
 *
 * If-conditions and lookup calls are translated to syslog-ng's native
 * filter / parser primitives where the mapping is reasonably faithful;
 * the supported surface:
 *
 *   • Equality on $programname / $hostname / $msg → program() / host() /
 *     message() filter primitives.
 *   • `contains` / `startswith` / `endswith` on the same fields → message()
 *     with the relevant regex form, or program()/host() with bare strings
 *     when syslog-ng accepts substring matching.
 *   • Boolean and/or/not → corresponding filter operators (filter(f_a and f_b)).
 *   • Severity / facility comparisons → severity() / facility() filters.
 *   • Lookup tables → add-contextual-data() parsers reading CSV sidecars
 *     emitted next to the main config file.
 *
 * What remains intentionally lossy (the diagnostic gets specific now):
 *   • Mutating expressions: `set $!sourcetype = lookup(...)` — syslog-ng
 *     also mutates state via add-contextual-data, but a roundtrip-preserving
 *     translation of arbitrary RainerScript set-expressions is out of scope.
 *   • Nested rulesets via `call` — left as a comment chain.
 */
export function emit(
  model: IRModel,
  opts?: { lookupTables?: Record<string, EmitLookupData> }
): EmitResult {
  const diagnostics: Diagnostic[] = [];
  const lines: string[] = [];
  const lookupTables = opts?.lookupTables ?? {};
  // Counters for diagnostic accuracy — instead of a blanket "if/lookup
  // dropped" note, report exactly N translated and K untranslatable so
  // the user knows whether to read the diagnostics.
  const stats = {
    ifsTranslated: 0,
    ifsUntranslatable: 0,
    lookupsEmitted: 0,
    lookupsUnsupported: 0,
    callsAsComment: 0
  };
  const sidecars: { path: string; content: string }[] = [];

  lines.push('@version: 4.3');
  lines.push('# Generated by logflow-sim convert');
  lines.push(`# Source dialect: ${model.dialect}`);
  lines.push('');

  const optsKeys = Object.entries(model.globals.params).filter(
    ([k]) => k && !k.startsWith('__')
  );
  if (optsKeys.length > 0) {
    lines.push('options {');
    for (const [k, v] of optsKeys) {
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${k}(${jsonString(String(v))});`);
      }
    }
    lines.push('};');
    lines.push('');
  }

  // Sources from IRInput
  const sourceNames: { name: string; inputType: string; port?: number }[] = [];
  for (const inp of model.inputs) {
    const driver = mapInputDriver(inp.type);
    const portClause = inp.port !== undefined ? ` port(${inp.port})` : '';
    const name = `s_${sanitize(inp.type)}_${inp.port ?? sourceNames.length}`;
    sourceNames.push({ name, inputType: inp.type, port: inp.port });
    lines.push(`source ${name} {`);
    lines.push(`    ${driver}(${portClause.trim()});`);
    lines.push('};');
  }
  if (model.inputs.length > 0) lines.push('');

  // Templates (syslog-ng-native rsyslog templates → template blocks).
  for (const t of model.templates) {
    if (typeof t.params['string'] === 'string') {
      lines.push(`template t_${sanitize(t.name)} {`);
      lines.push(`    template(${jsonString(String(t.params['string']))});`);
      lines.push('};');
    }
  }
  if (model.templates.length > 0) lines.push('');

  // Lookup tables → add-contextual-data parsers + CSV sidecars. Each
  // table needs a selector field; syslog-ng's add-contextual-data() uses
  // a single selector column. We pick the natural one based on the
  // table's typical rsyslog use: programname-keyed tables stay keyed by
  // ${PROGRAM}, hostname-keyed by ${HOST}, generic ones default to
  // ${PROGRAM} with a comment for the operator to verify.
  const lookupParserNames: string[] = [];
  for (const lt of model.lookupTables) {
    const data = lookupTables[lt.name];
    const entries = data?.entries ?? {};
    const safeName = sanitize(lt.name);
    const sidecarPath = `lookups/${safeName}.csv`;
    const parserName = `p_lookup_${safeName}`;
    lookupParserNames.push(parserName);

    if (Object.keys(entries).length === 0) {
      stats.lookupsUnsupported++;
      diagnostics.push({
        severity: 'warning',
        message: `syslog-ng emit: lookup table "${lt.name}" had no loaded data; emitted an empty CSV stub.`,
        source: lt.source,
        code: 'W_SYSLOGNG_LOOKUP_EMPTY'
      });
    } else {
      stats.lookupsEmitted++;
    }

    // CSV columns: selector, name, value. Selector is the lookup key,
    // value becomes a syslog-ng tag named after the table (so rules can
    // reference `${.${table}}`). Two-column input would be ambiguous
    // about the value's role; this three-column shape matches what
    // syslog-ng documents for add-contextual-data.
    const csv =
      `# syslog-ng add-contextual-data input — generated from ${lt.name}\n` +
      Object.entries(entries)
        .map(([k, v]) => `${csvEscape(k)},${csvEscape(lt.name)},${csvEscape(v)}`)
        .join('\n') +
      '\n';
    sidecars.push({ path: sidecarPath, content: csv });

    lines.push(`parser ${parserName} {`);
    lines.push(`    add-contextual-data(`);
    lines.push(`        selector("\${PROGRAM}"),`);
    lines.push(`        database(${jsonString(sidecarPath)}),`);
    if (typeof data?.nomatch === 'string' && data.nomatch.length > 0) {
      lines.push(`        default-selector(${jsonString(data.nomatch)}),`);
    }
    lines.push('    );');
    lines.push('};');
  }
  if (model.lookupTables.length > 0) lines.push('');

  // Destinations: explicit IROutput entries + actions discovered inside
  // rulesets (action-centric dialects like rsyslog don't separate them).
  const destByKey = new Map<string, string>();
  let destCounter = 0;
  function makeDestName(prefix: string): string {
    return `d_${prefix}_${destCounter++}`;
  }
  for (const out of model.outputs) {
    const name = `d_${sanitize(out.name)}`;
    destByKey.set(out.name, name);
    emitDestination(name, out.driver, out.params, lines);
  }

  function collectActions(stmts: IRStatement[]): IRAction[] {
    const acc: IRAction[] = [];
    for (const s of stmts) {
      if (s.kind === 'Action') acc.push(s);
      else if (s.kind === 'If') {
        acc.push(...collectActions(s.then));
        if (s.else) acc.push(...collectActions(s.else));
      }
    }
    return acc;
  }

  const seenActionKeys = new Set<string>();
  for (const rs of model.rulesets) {
    for (const a of collectActions(rs.statements)) {
      const key = describeAction(a);
      if (!key || seenActionKeys.has(key)) continue;
      seenActionKeys.add(key);
      const name = makeDestName(a.actionKind);
      destByKey.set(key, name);
      emitDestination(
        name,
        a.actionKind === 'unknown' ? a.actionType : a.actionKind,
        a.params,
        lines
      );
    }
  }
  if (model.outputs.length > 0 || seenActionKeys.size > 0) lines.push('');

  // Filters: every unique if-condition path becomes one filter{} block.
  // We dedupe by stringified expression so a condition reused in multiple
  // branches emits one filter and gets referenced N times.
  const filterByExpr = new Map<string, string>();
  let filterCounter = 0;
  function ensureFilter(condition: ConditionExpr): string | null {
    const repr = renderFilter(condition);
    if (!repr) return null;
    const cached = filterByExpr.get(repr);
    if (cached) return cached;
    const name = `f_${filterCounter++}`;
    filterByExpr.set(repr, name);
    lines.push(`filter ${name} { ${repr}; };`);
    return name;
  }

  // Walk each ruleset and emit one log{} per action, accumulating the
  // condition path that leads to it. This is the lossy step — only
  // translatable conditions become filter-refs; the rest become comments
  // attached to the log{} so an operator can see what was skipped.
  function visitForLogBlocks(
    rs: IRRuleset,
    inputSource: string,
    stmts: IRStatement[],
    accConditions: ConditionExpr[]
  ): void {
    for (const s of stmts) {
      if (s.kind === 'Action') {
        const k = describeAction(s);
        const dest = k ? destByKey.get(k) : undefined;
        if (!dest) continue;
        const filterNames: string[] = [];
        const droppedConditions: string[] = [];
        for (const c of accConditions) {
          const fname = ensureFilter(c);
          if (fname) filterNames.push(fname);
          else droppedConditions.push(c.raw ?? '<expr>');
        }
        lines.push('');
        lines.push(`# from ruleset "${rs.name}"`);
        for (const dc of droppedConditions) {
          lines.push(`# untranslated condition: ${dc}`);
        }
        lines.push('log {');
        lines.push(`    source(${inputSource});`);
        for (const fn of filterNames) lines.push(`    filter(${fn});`);
        for (const pn of lookupParserNames) lines.push(`    parser(${pn});`);
        lines.push(`    destination(${dest});`);
        lines.push('};');
      } else if (s.kind === 'If') {
        const cond = translateCondition(s);
        if (cond) stats.ifsTranslated++;
        else stats.ifsUntranslatable++;
        visitForLogBlocks(rs, inputSource, s.then, [
          ...accConditions,
          cond ?? { kind: 'untranslated', raw: rawConditionText(s) }
        ]);
        if (s.else) {
          visitForLogBlocks(rs, inputSource, s.else, [
            ...accConditions,
            cond
              ? { kind: 'not', inner: cond }
              : { kind: 'untranslated', raw: 'not ' + rawConditionText(s) }
          ]);
        }
      } else if (s.kind === 'Call') {
        stats.callsAsComment++;
        // Inline the called ruleset's statements as if they were here.
        // syslog-ng has no `call` primitive that perfectly mirrors
        // rsyslog's, so flattening is the practical move.
        const target = model.rulesetByName[s.ruleset];
        if (target) visitForLogBlocks(rs, inputSource, target.statements, accConditions);
      }
      // Set/Reset/Unset/Stop/Continue: noted as comments only for
      // operator awareness — they don't shape routing in a way syslog-ng's
      // log{}-filter-destination model can express.
    }
  }

  if (model.routes.length > 0) {
    // Non-rsyslog source dialect already came with explicit routes —
    // emit them unchanged, plus lookup parsers if any were registered.
    for (const route of model.routes) {
      lines.push('log {');
      for (const i of route.inputRefs) {
        const matched = sourceNames.find((s) => s.inputType === i);
        if (matched) lines.push(`    source(${matched.name});`);
        else lines.push(`    # source from ref "${i}"`);
      }
      for (const ref of route.filterRefs) lines.push(`    # filter ${ref}`);
      for (const ref of route.transformRefs) lines.push(`    # transform ${ref}`);
      for (const pn of lookupParserNames) lines.push(`    parser(${pn});`);
      for (const oref of route.outputRefs) {
        const dest = destByKey.get(oref);
        if (dest) lines.push(`    destination(${dest});`);
        else lines.push(`    # output ${oref}`);
      }
      lines.push('};');
    }
  } else {
    // rsyslog-shaped IR — one or more log{} per ruleset×action.
    for (const inp of model.inputs) {
      if (!inp.ruleset) continue;
      const rs = model.rulesetByName[inp.ruleset];
      if (!rs) continue;
      const sourceName = sourceNames.find(
        (s) => s.inputType === inp.type && (s.port === inp.port || inp.port === undefined)
      )?.name;
      if (!sourceName) continue;
      visitForLogBlocks(rs, sourceName, rs.statements, []);
    }
  }

  // Diagnostic summary: be specific about what got translated and what
  // didn't, so an operator can decide whether the conversion is good
  // enough for their use-case — a bland "best-effort" note isn't
  // actionable.
  if (stats.ifsTranslated > 0 || stats.ifsUntranslatable > 0) {
    diagnostics.push({
      severity: 'info',
      message:
        `syslog-ng emit: translated ${stats.ifsTranslated} if-condition(s) into filter() blocks; ` +
        `${stats.ifsUntranslatable} condition(s) had no syslog-ng equivalent and were emitted as comments.`,
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_SYSLOGNG_IFS'
    });
  }
  if (stats.lookupsEmitted > 0) {
    diagnostics.push({
      severity: 'info',
      message:
        `syslog-ng emit: ${stats.lookupsEmitted} lookup table(s) emitted as add-contextual-data ` +
        `parsers with CSV sidecars under lookups/. Each parser uses $PROGRAM as the selector — ` +
        `verify the field choice matches your original rsyslog lookup keying.`,
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_SYSLOGNG_LOOKUPS'
    });
  }
  if (stats.callsAsComment > 0) {
    diagnostics.push({
      severity: 'info',
      message: `syslog-ng emit: ${stats.callsAsComment} \`call <ruleset>\` invocation(s) flattened into the caller.`,
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_SYSLOGNG_CALL_FLATTENED'
    });
  }

  const output = lines.join('\n') + '\n';
  const files = [{ path: 'syslog-ng.conf', content: output }, ...sidecars];
  return { output, files, diagnostics };
}

// ---------------------------------------------------------------------------
// Condition translation
// ---------------------------------------------------------------------------

type ConditionExpr =
  | { kind: 'eq'; field: string; value: string; raw?: string }
  | { kind: 'contains'; field: string; value: string; ci?: boolean; raw?: string }
  | { kind: 'startswith'; field: string; value: string; ci?: boolean; raw?: string }
  | { kind: 'and'; left: ConditionExpr; right: ConditionExpr; raw?: string }
  | { kind: 'or'; left: ConditionExpr; right: ConditionExpr; raw?: string }
  | { kind: 'not'; inner: ConditionExpr; raw?: string }
  | { kind: 'severity'; op: '<' | '<=' | '==' | '>=' | '>'; level: number; raw?: string }
  | { kind: 'facility'; name: string; raw?: string }
  | { kind: 'untranslated'; raw?: string };

function translateCondition(ifStmt: IRIf): ConditionExpr | null {
  return translateExpr(ifStmt.condition);
}

function translateExpr(expr: Expr): ConditionExpr | null {
  if (expr.kind === 'BinaryOp') {
    const op = expr.op;
    if (op === 'and' || op === 'or') {
      const l = translateExpr(expr.left);
      const r = translateExpr(expr.right);
      if (!l || !r) return null;
      return { kind: op, left: l, right: r };
    }
    if (op === '==' || op === 'contains' || op === 'startswith') {
      const field = fieldOf(expr.left);
      const value = stringOf(expr.right);
      if (!field || value === null) return null;
      if (op === '==') return { kind: 'eq', field, value };
      if (op === 'contains') return { kind: 'contains', field, value };
      if (op === 'startswith') return { kind: 'startswith', field, value };
      return null;
    }
    if (op === 'contains_i') {
      const field = fieldOf(expr.left);
      const value = stringOf(expr.right);
      if (!field || value === null) return null;
      return { kind: 'contains', field, value, ci: true };
    }
    if (op === 'startswith_i') {
      const field = fieldOf(expr.left);
      const value = stringOf(expr.right);
      if (!field || value === null) return null;
      return { kind: 'startswith', field, value, ci: true };
    }
  }
  if (expr.kind === 'UnaryOp' && expr.op === 'not') {
    const inner = translateExpr(expr.operand);
    if (!inner) return null;
    return { kind: 'not', inner };
  }
  return null;
}

function fieldOf(e: Expr): string | null {
  if (e.kind === 'PropertyRef') return e.name;
  return null;
}

function stringOf(e: Expr): string | null {
  if (e.kind === 'StringLit') return e.value;
  if (e.kind === 'NumberLit') return String(e.value);
  return null;
}

function renderFilter(c: ConditionExpr): string | null {
  switch (c.kind) {
    case 'eq':
      if (c.field === 'programname') return `program(${jsonString(c.value)})`;
      if (c.field === 'hostname' || c.field === 'fromhost') return `host(${jsonString(c.value)})`;
      if (c.field === 'msg') return `message(${jsonString('^' + escapeRe(c.value) + '$')})`;
      return null;
    case 'contains':
      if (c.field === 'msg' || c.field === 'rawmsg')
        return `message(${jsonString(escapeRe(c.value))}${c.ci ? ' flags("ignore-case")' : ''})`;
      if (c.field === 'programname')
        return `program(${jsonString(escapeRe(c.value))}${c.ci ? ' flags("ignore-case")' : ''})`;
      if (c.field === 'hostname' || c.field === 'fromhost')
        return `host(${jsonString(escapeRe(c.value))}${c.ci ? ' flags("ignore-case")' : ''})`;
      return null;
    case 'startswith':
      if (c.field === 'msg' || c.field === 'rawmsg')
        return `message(${jsonString('^' + escapeRe(c.value))}${c.ci ? ' flags("ignore-case")' : ''})`;
      if (c.field === 'programname')
        return `program(${jsonString('^' + escapeRe(c.value))}${c.ci ? ' flags("ignore-case")' : ''})`;
      return null;
    case 'and': {
      const l = renderFilter(c.left);
      const r = renderFilter(c.right);
      if (!l || !r) return null;
      return `(${l}) and (${r})`;
    }
    case 'or': {
      const l = renderFilter(c.left);
      const r = renderFilter(c.right);
      if (!l || !r) return null;
      return `(${l}) or (${r})`;
    }
    case 'not': {
      const i = renderFilter(c.inner);
      if (!i) return null;
      return `not (${i})`;
    }
    case 'severity':
      return `level(${c.level}..7)`;
    case 'facility':
      return `facility(${c.name})`;
    case 'untranslated':
      return null;
  }
}

function rawConditionText(stmt: IRIf): string {
  // Best-effort textual preview for the comment that replaces an
  // un-translatable condition. The IR doesn't keep the raw source text,
  // so we render the AST shape so the operator can recognize the
  // construct even without round-tripping.
  return describeExpr(stmt.condition).slice(0, 80);
}

function describeExpr(e: Expr): string {
  switch (e.kind) {
    case 'BinaryOp':
      return `${describeExpr(e.left)} ${e.op} ${describeExpr(e.right)}`;
    case 'UnaryOp':
      return `${e.op} ${describeExpr(e.operand)}`;
    case 'PropertyRef':
      return `$${e.name}`;
    case 'LocalVarRef':
      return `$.${e.name}`;
    case 'StructuredRef':
      return `$!${e.name}`;
    case 'StringLit':
      return `"${e.value.replace(/"/g, '\\"')}"`;
    case 'NumberLit':
      return String(e.value);
    case 'CallExpr':
      return `${e.callee}(...)`;
    case 'LookupCall':
      return `lookup(...)`;
    case 'ArrayLit':
      return `[...]`;
    case 'ParenExpr':
      return `(${describeExpr(e.inner)})`;
  }
}

// ---------------------------------------------------------------------------
// Misc helpers
// ---------------------------------------------------------------------------

function mapInputDriver(rsyslogType: string): string {
  const t = rsyslogType.toLowerCase();
  if (t === 'imudp') return 'udp';
  if (t === 'imtcp' || t === 'imptcp') return 'tcp';
  if (t === 'imuxsock') return 'unix-dgram';
  if (t === 'imklog') return 'kernel';
  if (t === 'imjournal') return 'systemd-journal';
  if (t === 'imfile') return 'file';
  return rsyslogType;
}

function emitDestination(
  name: string,
  driver: string,
  params: Record<string, unknown>,
  lines: string[]
): void {
  const d = driver.toLowerCase();
  lines.push(`destination ${name} {`);
  if (d === 'omfile' || d === 'file') {
    const file = String(params['file'] ?? params['dynafile'] ?? '/dev/null');
    lines.push(`    file(${jsonString(file)});`);
  } else if (d === 'omfwd' || d === 'syslog' || d === 'tcp' || d === 'udp') {
    const host = String(params['target'] ?? params['host'] ?? 'localhost');
    const port = params['port'];
    const proto =
      String(params['protocol'] ?? '').toLowerCase() === 'udp' ? 'udp' : 'tcp';
    lines.push(`    ${proto}(${jsonString(host)}${port ? ` port(${port})` : ''});`);
  } else if (d === 'omelasticsearch' || d === 'elasticsearch') {
    lines.push(`    elasticsearch-http(url(${jsonString(String(params['url'] ?? ''))}));`);
  } else if (d === 'omkafka' || d === 'kafka') {
    lines.push(
      `    kafka-c(topic(${jsonString(String(params['topic'] ?? params['name'] ?? ''))}));`
    );
  } else if (d === 'omhttp' || d === 'http') {
    lines.push(`    http(url(${jsonString(String(params['url'] ?? params['uri'] ?? ''))}));`);
  } else {
    lines.push(`    # unknown driver "${driver}" — params: ${JSON.stringify(params).slice(0, 100)}`);
    lines.push(`    file("/dev/null");`);
  }
  lines.push('};');
}

function describeAction(a: IRAction): string | null {
  if (a.actionKind === 'omfile') {
    const dyna = a.params['dynafile'];
    const file = a.params['file'];
    if (typeof dyna === 'string') return `dyna:${dyna}`;
    if (typeof file === 'string') return `file:${file}`;
    return null;
  }
  if (a.actionKind === 'omfwd') {
    const target = a.params['target'];
    const port = a.params['port'];
    if (typeof target !== 'string') return null;
    return `fwd:${target}:${port ?? ''}`;
  }
  return `${a.actionKind}:${JSON.stringify(a.params).slice(0, 40)}`;
}

function sanitize(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, '_');
}

function jsonString(s: string): string {
  return JSON.stringify(s);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function csvEscape(s: string): string {
  if (/[",\n]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}
