import type { IRModel } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';

/**
 * Emit a normalized IR as NXLog configuration.
 *
 * Mapping:
 *   IRInput  → <Input name>  Module <type>  Port N </Input>
 *   IROutput → <Output name> Module <driver> Host X Port N </Output>
 *   IRRoute  → <Route name>  Path src => filt => dest </Route>
 *
 * For rsyslog-shaped IR with rulesets, we synthesize one Route per input
 * binding, listing every distinct output the ruleset's actions reach.
 */
export function emit(model: IRModel): { output: string; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const lines: string[] = [];
  lines.push('## Generated by logflow-sim convert');
  lines.push(`## Source dialect: ${model.dialect}`);
  lines.push('');

  // Top-level globals
  for (const [k, v] of Object.entries(model.globals.params)) {
    if (k.startsWith('__')) continue;
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
      lines.push(`${titleize(k)} ${v}`);
    }
  }
  if (Object.keys(model.globals.params).length > 0) lines.push('');

  // Input blocks
  const inputNames = new Map<string, string>();
  for (const inp of model.inputs) {
    const name = `in_${sanitize(inp.type)}_${inp.port ?? inputNames.size}`;
    inputNames.set(inp.id, name);
    lines.push(`<Input ${name}>`);
    lines.push(`    Module ${mapInputModule(inp.type)}`);
    if (inp.port !== undefined) lines.push(`    Port ${inp.port}`);
    for (const [k, v] of Object.entries(inp.params)) {
      if (['type', 'port'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${titleize(k)} ${v}`);
      }
    }
    lines.push('</Input>');
    lines.push('');
  }

  // Output blocks (from native IROutputs first)
  const outputNames = new Map<string, string>();
  for (const out of model.outputs) {
    const name = `out_${sanitize(out.name)}`;
    outputNames.set(out.name, name);
    lines.push(`<Output ${name}>`);
    lines.push(`    Module ${mapOutputModule(out.driver)}`);
    for (const [k, v] of Object.entries(out.params)) {
      if (['name', 'type'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        lines.push(`    ${titleize(k)} ${v}`);
      }
    }
    lines.push('</Output>');
    lines.push('');
  }

  // Synthesize Outputs from rsyslog actions when no IROutput exists.
  let synthCounter = 0;
  const synthOutputs = new Map<string, string>();
  function visit(stmts: import('../../ir/model.js').IRStatement[]): void {
    for (const s of stmts) {
      if (s.kind === 'If') {
        visit(s.then);
        if (s.else) visit(s.else);
        continue;
      }
      if (s.kind !== 'Action') continue;
      const key = `${s.actionKind}:${JSON.stringify(s.params)}`;
      if (synthOutputs.has(key)) continue;
      const name = `out_synth_${synthCounter++}`;
      synthOutputs.set(key, name);
      lines.push(`<Output ${name}>`);
      lines.push(`    Module ${mapOutputModule(s.actionType || s.actionKind)}`);
      for (const [k, v] of Object.entries(s.params)) {
        if (k === 'type') continue;
        if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
          lines.push(`    ${titleize(k)} ${v}`);
        }
      }
      lines.push('</Output>');
      lines.push('');
    }
  }
  for (const rs of model.rulesets) visit(rs.statements);

  // Routes
  if (model.routes.length > 0) {
    for (const r of model.routes) {
      const routeName = sanitize(r.name ?? r.id);
      lines.push(`<Route ${routeName}>`);
      const ins = r.inputRefs
        .map((n) => {
          const matched = [...inputNames.values()].find((v) => v.endsWith('_' + sanitize(n)) || v.includes(sanitize(n)));
          return matched ?? n;
        })
        .filter(Boolean);
      const outs = r.outputRefs.map((n) => outputNames.get(n) ?? n).filter(Boolean);
      const pieces = [
        ins.join(', ') || '*',
        ...r.transformRefs,
        outs.join(', ') || '*'
      ];
      lines.push(`    Path ${pieces.join(' => ')}`);
      lines.push('</Route>');
      lines.push('');
    }
  } else {
    // rsyslog-style: one route per input → all outputs synth'd for its ruleset.
    let routeIdx = 1;
    for (const inp of model.inputs) {
      const rsName = inp.ruleset;
      if (!rsName) continue;
      const rs = model.rulesetByName[rsName];
      if (!rs) continue;
      const outNames = new Set<string>();
      function collect(stmts: import('../../ir/model.js').IRStatement[]): void {
        for (const s of stmts) {
          if (s.kind === 'If') {
            collect(s.then);
            if (s.else) collect(s.else);
            continue;
          }
          if (s.kind !== 'Action') continue;
          const key = `${s.actionKind}:${JSON.stringify(s.params)}`;
          const n = synthOutputs.get(key);
          if (n) outNames.add(n);
        }
      }
      collect(rs.statements);
      if (outNames.size === 0) continue;
      lines.push(`<Route route_${routeIdx++}>`);
      lines.push(
        `    Path ${inputNames.get(inp.id)} => ${[...outNames].join(', ')}`
      );
      lines.push('</Route>');
      lines.push('');
    }
  }

  if (model.inputs.length === 0 && model.outputs.length === 0 && synthOutputs.size === 0) {
    diagnostics.push({
      severity: 'info',
      message: 'No inputs or outputs to emit — the converted config is empty.',
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_CONVERT_EMPTY'
    });
  }

  return { output: lines.join('\n') + '\n', diagnostics };
}

function mapInputModule(t: string): string {
  const m: Record<string, string> = {
    imudp: 'im_udp',
    imtcp: 'im_tcp',
    imptcp: 'im_tcp',
    udp: 'im_udp',
    tcp: 'im_tcp',
    imfile: 'im_file',
    imjournal: 'im_systemd',
    syslog: 'im_udp'
  };
  return m[t.toLowerCase()] ?? t;
}

function mapOutputModule(d: string): string {
  const m: Record<string, string> = {
    omfile: 'om_file',
    omfwd: 'om_udp',
    omkafka: 'om_kafka',
    omhttp: 'om_http',
    omelasticsearch: 'om_elasticsearch',
    file: 'om_file',
    udp: 'om_udp',
    tcp: 'om_tcp',
    kafka: 'om_kafka',
    http: 'om_http'
  };
  return m[d.toLowerCase()] ?? d;
}

function titleize(s: string): string {
  return s
    .split(/[._-]/)
    .map((p) => (p ? p.charAt(0).toUpperCase() + p.slice(1) : p))
    .join('');
}

function sanitize(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, '_');
}
