/**
 * Emit an IR as a Fluentd td-agent.conf.
 *
 * Output shape:
 *   <source>
 *     @type forward
 *     port 24224
 *   </source>
 *   <filter ...>
 *     @type record_transformer
 *     ...
 *   </filter>
 *   <match **>
 *     @type elasticsearch
 *     hosts ...
 *   </match>
 *
 * Lookup tables emit as `record_transformer` filters with inline `<record>`
 * blocks — Fluentd's idiomatic way to add a derived field per record.
 */

import type { IRModel, IRStatement } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';
import type { EmitLookupData, EmitResult } from '../types.js';

export function emit(
  model: IRModel,
  opts?: { lookupTables?: Record<string, EmitLookupData> }
): EmitResult {
  const diagnostics: Diagnostic[] = [];
  const lookups = opts?.lookupTables ?? {};
  const out: string[] = [];
  out.push('# Generated by logflow-sim convert');
  out.push(`# Source dialect: ${model.dialect ?? 'unknown'}`);
  out.push('');

  // Sources from IRInput
  for (const inp of model.inputs) {
    out.push('<source>');
    out.push(`  @type ${mapInputType(inp.type)}`);
    if (inp.port !== undefined) out.push(`  port ${inp.port}`);
    const tag = String(inp.params['name'] ?? '');
    if (tag) out.push(`  tag ${tag}`);
    for (const [k, v] of Object.entries(inp.params)) {
      if (k === 'name' || k === '@type' || k === 'tag' || k === 'port') continue;
      if (typeof v === 'string' || typeof v === 'number') {
        out.push(`  ${k} ${String(v)}`);
      }
    }
    out.push('</source>');
    out.push('');
  }

  // From rsyslog: synthesize one source per imudp/imtcp input.
  // already handled above when source dialect provides inputs.

  // Filters (existing fluentd-side IRModules or synthesized for lookups).
  for (const mod of model.modules) {
    if (!mod.load.startsWith('filter:') && !mod.load.startsWith('processor:')) continue;
    const t = mod.load.split(':', 2)[1];
    const pattern = String(mod.params['pattern'] ?? '**');
    out.push(`<filter ${pattern}>`);
    out.push(`  @type ${t}`);
    for (const [k, v] of Object.entries(mod.params)) {
      if (['name', 'pattern', '@type'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number') {
        out.push(`  ${k} ${String(v)}`);
      }
    }
    out.push('</filter>');
    out.push('');
  }

  // Lookups → record_transformer with an inline hash. Tiny tables only;
  // large ones get a diagnostic to convert to a `record_modifier` filter
  // backed by an external file.
  for (const lt of model.lookupTables) {
    const data = lookups[lt.name];
    if (!data || !data.entries) continue;
    if (Object.keys(data.entries).length > 200) {
      diagnostics.push({
        severity: 'warning',
        message:
          `Fluentd emit: lookup "${lt.name}" inlined into record_transformer. Consider a ` +
          `record_modifier filter with file-backed mapping for large tables.`,
        source: { file: '<emit>', line: 0, col: 0, offset: 0, length: 0 },
        code: 'W_FLUENTD_LOOKUP_BIG'
      });
    }
    const literal = Object.entries(data.entries)
      .map(([k, v]) => `'${escSingle(k)}' => '${escSingle(v)}'`)
      .join(', ');
    out.push(`<filter **>`);
    out.push(`  @type record_transformer`);
    out.push(`  enable_ruby true`);
    out.push(`  <record>`);
    out.push(
      `    ${lt.name} \${ {${literal}}[record["programname"]] || '${data.nomatch ?? ''}' }`
    );
    out.push(`  </record>`);
    out.push(`</filter>`);
    out.push('');
  }

  // Matches from IROutput
  for (const o of model.outputs) {
    const pattern = String(o.params['pattern'] ?? '**');
    out.push(`<match ${pattern}>`);
    out.push(`  @type ${mapOutputType(o.driver ?? o.actionKind)}`);
    for (const [k, v] of Object.entries(o.params)) {
      if (['name', 'pattern', '@type'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number') {
        out.push(`  ${k} ${String(v)}`);
      }
    }
    out.push('</match>');
    out.push('');
  }

  // From rsyslog: each ruleset's action set becomes a single match block.
  // We collapse if-conditions away — Fluentd's tag-routing model doesn't
  // have a direct equivalent of rsyslog's expression-based conditionals.
  if (model.outputs.length === 0) {
    const actions = collectActions(model);
    for (const a of actions) {
      out.push(`<match **>`);
      out.push(`  @type ${mapOutputType(a.actionKind || 'file')}`);
      if (a.actionKind === 'omfile') {
        out.push(`  path ${String(a.params['file'] ?? a.params['dynafile'] ?? '/var/log/out')}`);
      } else if (a.actionKind === 'omfwd') {
        const host = String(a.params['target'] ?? 'localhost');
        const port = String(a.params['port'] ?? '24224');
        out.push(`  <server>`);
        out.push(`    host ${host}`);
        out.push(`    port ${port}`);
        out.push(`  </server>`);
      }
      out.push(`</match>`);
      out.push('');
    }
  }

  const output = out.join('\n');
  return {
    output,
    files: [{ path: 'td-agent.conf', content: output }],
    diagnostics
  };
}

function mapInputType(t: string): string {
  const x = t.toLowerCase();
  if (x === 'imudp' || x === 'imtcp' || x === 'syslog') return 'syslog';
  if (x === 'imfile' || x === 'log' || x === 'file' || x === 'filelog') return 'tail';
  if (x === 'imjournal' || x === 'journald') return 'systemd';
  if (x === 'imhttp' || x === 'http') return 'http';
  if (x === 'imkafka' || x === 'kafka') return 'kafka_group';
  return x;
}

function mapOutputType(d: string): string {
  const x = d.toLowerCase();
  if (x === 'omfile' || x === 'file') return 'file';
  if (x === 'omfwd' || x === 'syslog' || x === 'tcp' || x === 'udp') return 'forward';
  if (x === 'omelasticsearch' || x === 'elasticsearch') return 'elasticsearch';
  if (x === 'omkafka' || x === 'kafka') return 'kafka2';
  if (x === 'omhttp' || x === 'http' || x === 'loki') return 'http';
  return x;
}

function collectActions(model: IRModel): { actionKind: string; params: Record<string, unknown> }[] {
  const out: { actionKind: string; params: Record<string, unknown> }[] = [];
  function visit(stmts: IRStatement[]): void {
    for (const s of stmts) {
      if (s.kind === 'If') {
        visit(s.then);
        if (s.else) visit(s.else);
      } else if (s.kind === 'Action') {
        out.push({ actionKind: s.actionKind, params: s.params as Record<string, unknown> });
      }
    }
  }
  for (const rs of model.rulesets) visit(rs.statements);
  return out;
}

function escSingle(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
