import type { IRModel, IRStatement } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';

/**
 * Emit a normalized IR as a Logstash pipeline config.
 *
 * Logstash configs have a rigid three-section structure:
 *
 *   input  { <plugin> { key => "value" … } … }
 *   filter { <plugin> { … } … }   (optional)
 *   output { <plugin> { … } … }
 *
 * - rsyslog actions become output plugins; the Logstash pipeline is
 *   linear, so every output sees every record regardless of which input
 *   produced it.
 * - rsyslog if/condition logic doesn't carry over — `if` exists in
 *   Logstash but uses Ruby-ish syntax we don't map yet. We emit a comment
 *   for each lost condition.
 */
export function emit(model: IRModel): { output: string; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const lines: string[] = [];
  lines.push('# Generated by logflow-sim convert');
  lines.push(`# Source dialect: ${model.dialect}`);
  lines.push('');

  // input { … }
  lines.push('input {');
  for (const inp of model.inputs) {
    const plugin = mapInputPlugin(inp.type);
    lines.push(`  ${plugin} {`);
    if (inp.port !== undefined) lines.push(`    port => ${inp.port}`);
    for (const [k, v] of Object.entries(inp.params)) {
      if (['type', 'port', '_tag', 'name'].includes(k)) continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        const val = typeof v === 'string' ? quote(v) : String(v);
        lines.push(`    ${k} => ${val}`);
      }
    }
    lines.push('  }');
  }
  lines.push('}');
  lines.push('');

  // filter { … } — only when we have something to emit (from IRModule filter:* entries
  // or rsyslog set/reset/unset semantics).
  const filterPlugins = model.modules.filter((m) => m.load.startsWith('filter:'));
  const rsyslogMutations = collectRsyslogMutations(model);
  if (filterPlugins.length > 0 || rsyslogMutations.length > 0) {
    lines.push('filter {');
    for (const fp of filterPlugins) {
      const name = fp.load.replace(/^filter:/, '');
      lines.push(`  ${name} {`);
      for (const [k, v] of Object.entries(fp.params)) {
        if (k === 'name') continue;
        if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
          lines.push(`    ${k} => ${typeof v === 'string' ? quote(v) : String(v)}`);
        }
      }
      lines.push('  }');
    }
    if (rsyslogMutations.length > 0) {
      lines.push('  mutate {');
      lines.push('    add_field => {');
      for (const { name, value } of rsyslogMutations) {
        lines.push(`      ${quote('[' + name + ']')} => ${quote(value)}`);
      }
      lines.push('    }');
      lines.push('  }');
    }
    lines.push('}');
    lines.push('');
  }

  // output { … }
  lines.push('output {');
  const emitted = new Set<string>();
  for (const out of model.outputs) {
    emitOutputPlugin(out.driver, out.params, lines);
    emitted.add(out.name);
  }
  function walk(stmts: IRStatement[]): void {
    for (const s of stmts) {
      if (s.kind === 'If') {
        // Logstash supports if [field] == "x" { … }; we can't map rsyslog's
        // expression AST 1:1, so emit a comment marker and walk the body.
        lines.push(`  # if (...) — original condition not translated`);
        walk(s.then);
        if (s.else) {
          lines.push(`  # else`);
          walk(s.else);
        }
        continue;
      }
      if (s.kind !== 'Action') continue;
      const key = `${s.actionKind}:${JSON.stringify(s.params)}`;
      if (emitted.has(key)) continue;
      emitted.add(key);
      emitOutputPlugin(s.actionType || s.actionKind, s.params as Record<string, unknown>, lines);
    }
  }
  for (const rs of model.rulesets) walk(rs.statements);
  lines.push('}');

  if (emitted.size === 0) {
    diagnostics.push({
      severity: 'info',
      message: 'No outputs emitted — source IR has no actions or outputs.',
      source: { file: '<convert>', line: 0, col: 0, offset: 0, length: 0 },
      code: 'I_CONVERT_NO_OUTPUTS'
    });
  }

  return { output: lines.join('\n') + '\n', diagnostics };
}

function emitOutputPlugin(driver: string, params: Record<string, unknown>, lines: string[]): void {
  const plugin = mapOutputPlugin(driver);
  lines.push(`  ${plugin} {`);
  for (const [k, v] of Object.entries(params)) {
    if (['type', 'name'].includes(k)) continue;
    if (typeof v === 'string') lines.push(`    ${k} => ${quote(v)}`);
    else if (typeof v === 'number' || typeof v === 'boolean') lines.push(`    ${k} => ${v}`);
  }
  lines.push('  }');
}

function collectRsyslogMutations(model: IRModel): { name: string; value: string }[] {
  const out: { name: string; value: string }[] = [];
  function walk(stmts: IRStatement[]): void {
    for (const s of stmts) {
      if (s.kind === 'If') {
        walk(s.then);
        if (s.else) walk(s.else);
        continue;
      }
      if ((s.kind === 'Set' || s.kind === 'Reset') && s.targetKind === 'structured') {
        // Best effort: capture the IR target name. The actual value is an
        // Expr — we can't safely render it without an Expr emitter, so we
        // record it as `<computed>` and surface it as a diagnostic.
        out.push({ name: s.targetName, value: '<computed>' });
      }
    }
  }
  for (const rs of model.rulesets) walk(rs.statements);
  return out;
}

function mapInputPlugin(t: string): string {
  const m: Record<string, string> = {
    imudp: 'udp',
    imtcp: 'tcp',
    imptcp: 'tcp',
    imfile: 'file',
    imjournal: 'journald',
    syslog: 'syslog'
  };
  return m[t.toLowerCase()] ?? t.toLowerCase();
}

function mapOutputPlugin(d: string): string {
  const m: Record<string, string> = {
    omfile: 'file',
    omfwd: 'tcp',
    omkafka: 'kafka',
    omhttp: 'http',
    omelasticsearch: 'elasticsearch'
  };
  return m[d.toLowerCase()] ?? d.toLowerCase();
}

function quote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}
