import type { IRModel, IRRuleset, IRStatement, IRAction } from '../../ir/model.js';
import type { Diagnostic } from '../../diagnostics.js';

/**
 * Emit a normalized IR back as rsyslog (RainerScript) configuration.
 *
 * We don't try to round-trip byte-for-byte — instead we generate clean,
 * idiomatic modern RainerScript that captures the same routing
 * semantics. Inputs become `input(...)`, outputs become `action(...)`,
 * routes become rulesets with the route's filters as guarded actions.
 *
 * Models produced by NON-rsyslog dialects (syslog-ng / Fluent Bit / …) are
 * also emit-able: their inputs/outputs/routes get folded into a synthetic
 * `_converted` ruleset.
 */
export function emit(model: IRModel): { output: string; diagnostics: Diagnostic[] } {
  const diagnostics: Diagnostic[] = [];
  const lines: string[] = [];
  lines.push('# Generated by logflow-sim convert');
  lines.push(`# Source dialect: ${model.dialect}`);
  lines.push('');

  // Modules
  for (const mod of model.modules) {
    const kv = renderParams(mod.params);
    lines.push(`module(${kv})`);
  }
  if (model.modules.length > 0) lines.push('');

  // Globals
  if (Object.keys(model.globals.params).length > 0) {
    const kv = renderParams(model.globals.params);
    if (kv) lines.push(`global(${kv})`);
  }
  if (model.globals.defaultRuleset) {
    lines.push(`$DefaultRuleset ${model.globals.defaultRuleset}`);
  }
  lines.push('');

  // Templates
  for (const tpl of model.templates) {
    if (!tpl.name) continue;
    if (tpl.type === 'list' && tpl.parts) {
      lines.push(`template(name="${tpl.name}" type="list") {`);
      for (const p of tpl.parts) {
        if (p.kind === 'constant') {
          lines.push(`    constant(value=${JSON.stringify(p.value)})`);
        } else {
          lines.push(`    property(name="${p.name}")`);
        }
      }
      lines.push('}');
    } else if (typeof tpl.string === 'string') {
      lines.push(
        `template(name="${tpl.name}" type="string" string=${JSON.stringify(tpl.string)})`
      );
    }
  }
  if (model.templates.length > 0) lines.push('');

  // Lookup tables
  for (const lt of model.lookupTables) {
    lines.push(
      `lookup_table(name="${lt.name}" file="${lt.file}"${lt.reloadOnHUP ? ' reloadOnHUP="on"' : ''})`
    );
  }
  if (model.lookupTables.length > 0) lines.push('');

  // Inputs
  for (const inp of model.inputs) {
    const pieces = [`type="${inp.type}"`];
    if (inp.port !== undefined) pieces.push(`port="${inp.port}"`);
    if (inp.ruleset) pieces.push(`ruleset="${inp.ruleset}"`);
    for (const [k, v] of Object.entries(inp.params)) {
      if (k === 'type' || k === 'port' || k === 'ruleset') continue;
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        pieces.push(`${k}="${escapeQ(String(v))}"`);
      }
    }
    lines.push(`input(${pieces.join(' ')})`);
  }
  if (model.inputs.length > 0) lines.push('');

  // Rulesets (native rsyslog statements)
  for (const rs of model.rulesets) {
    lines.push(`ruleset(name="${rs.name}") {`);
    for (const s of rs.statements) emitStatement(s, lines, '    ');
    lines.push('}');
    lines.push('');
  }

  // For dialects whose IR uses routes/outputs instead of rulesets, fold them.
  if (model.rulesets.length === 0 && (model.routes.length > 0 || model.outputs.length > 0)) {
    diagnostics.push({
      severity: 'info',
      message: `Source dialect "${model.dialect}" has no rsyslog rulesets — converted via synthetic _converted ruleset`,
      source: model.outputs[0]?.source ?? {
        file: '<convert>',
        line: 0,
        col: 0,
        offset: 0,
        length: 0
      },
      code: 'I_CONVERT_SYNTH_RULESET'
    });
    lines.push('# === synthetic ruleset bridging routes from source dialect ===');
    lines.push('ruleset(name="_converted") {');
    for (const route of model.routes) {
      // Emit each route as a block of actions; filters as a comment until
      // we map them properly (rsyslog uses if-conditions, not named filters).
      if (route.filterRefs.length > 0) {
        lines.push(`    # route ${route.name ?? route.id} filters: ${route.filterRefs.join(', ')}`);
      }
      for (const oref of route.outputRefs) {
        const out = model.outputByName[oref];
        if (!out) continue;
        const pieces = [`type="${out.actionKind === 'unknown' ? out.driver : out.actionKind}"`];
        for (const [k, v] of Object.entries(out.params)) {
          if (k === 'type' || k === 'name' || k === 'inputs') continue;
          if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
            pieces.push(`${k}="${escapeQ(String(v))}"`);
          }
        }
        lines.push(`    action(${pieces.join(' ')})`);
      }
    }
    lines.push('}');
  }

  return { output: lines.join('\n') + '\n', diagnostics };
}

function emitStatement(s: IRStatement, lines: string[], indent: string): void {
  switch (s.kind) {
    case 'If':
      lines.push(`${indent}if (...) then {`);
      for (const t of s.then) emitStatement(t, lines, indent + '    ');
      if (s.else) {
        lines.push(`${indent}} else {`);
        for (const e of s.else) emitStatement(e, lines, indent + '    ');
      }
      lines.push(`${indent}}`);
      break;
    case 'Set':
      lines.push(`${indent}set ${s.targetKind === 'local' ? '$.' : '$!'}${s.targetName} = ...;`);
      break;
    case 'Reset':
      lines.push(`${indent}reset ${s.targetKind === 'local' ? '$.' : '$!'}${s.targetName} = ...;`);
      break;
    case 'Unset':
      lines.push(`${indent}unset ${s.targetKind === 'local' ? '$.' : '$!'}${s.targetName};`);
      break;
    case 'Stop':
      lines.push(`${indent}stop`);
      break;
    case 'Continue':
      lines.push(`${indent}continue`);
      break;
    case 'Call':
      lines.push(`${indent}call ${s.ruleset}`);
      break;
    case 'Action':
      emitAction(s, lines, indent);
      break;
    case 'ReloadLookupTable':
      lines.push(`${indent}reload_lookup_table("${s.table}")`);
      break;
    case 'LegacySelector':
      lines.push(`${indent}${s.facspec}  ${s.target}`);
      break;
    case 'Unknown':
      // Preserve verbatim — `raw` is whatever the parser couldn't model.
      lines.push(`${indent}${s.raw}`);
      break;
  }
}

function emitAction(a: IRAction, lines: string[], indent: string): void {
  const pieces = [`type="${a.actionType || a.actionKind}"`];
  for (const [k, v] of Object.entries(a.params)) {
    if (k === 'type') continue;
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
      pieces.push(`${k}="${escapeQ(String(v))}"`);
    }
  }
  lines.push(`${indent}action(${pieces.join(' ')})`);
}

function renderParams(params: Record<string, unknown>): string {
  const out: string[] = [];
  for (const [k, v] of Object.entries(params)) {
    if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
      out.push(`${k}="${escapeQ(String(v))}"`);
    }
  }
  return out.join(' ');
}

function escapeQ(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
